const ACTIONS_TYPES = {
//MOVIES
	//Get All
		GET_MOVIES_ACTIONS: "GET_MOVIES_ACTIONS",
		GET_MOVIES_REQUEST: "GET_MOVIES_REQUEST",
		GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
		GET_MOVIES_ERROR: "GET_MOVIES_ERROR",
	//Create
		POST_MOVIE_ACTIONS: "POST_MOVIE_ACTIONS",
		POST_MOVIE_REQUEST: "POST_MOVIE_REQUEST",
		POST_MOVIE_SUCCESS: "POST_MOVIE_SUCCESS",
		POST_MOVIE_ERROR: "POST_MOVIE_ERROR",
	//Update
		PUT_MOVIE_ACTIONS: "PUT_MOVIE_ACTIONS",
		PUT_MOVIE_REQUEST: "PUT_MOVIE_REQUEST",
		PUT_MOVIE_SUCCESS: "PUT_MOVIE_SUCCESS",
		PUT_MOVIE_ERROR: "PUT_MOVIE_ERROR",
	//Delete
		DEL_MOVIE_ACTIONS: "DEL_MOVIE_ACTIONS",
		DEL_MOVIE_REQUEST: "DEL_MOVIE_REQUEST",
		DEL_MOVIE_SUCCESS: "DEL_MOVIE_SUCCESS",
		DEL_MOVIE_ERROR: "DEL_MOVIE_ERROR",

//Actors
	//Get All
		GET_ACTORS_ACTIONS: "GET_ACTORS_ACTIONS",
		GET_ACTORS_REQUEST: "GET_ACTORS_REQUEST",
		GET_ACTORS_SUCCESS: "GET_ACTORS_SUCCESS",
		GET_ACTORS_ERROR: "GET_ACTORS_ERROR",
//Create
		POST_ACTOR_ACTIONS: "POST_ACTOR_ACTIONS",
		POST_ACTOR_REQUEST: "POST_ACTOR_REQUEST",
		POST_ACTOR_SUCCESS: "POST_ACTOR_SUCCESS",
		POST_ACTOR_ERROR: "POST_ACTOR_ERROR",
//Update
		PUT_ACTOR_ACTIONS: "PUT_ACTOR_ACTIONS",
		PUT_ACTOR_REQUEST: "PUT_ACTOR_REQUEST",
		PUT_ACTOR_SUCCESS: "PUT_ACTOR_SUCCESS",
		PUT_ACTOR_ERROR: "PUT_ACTOR_ERROR",
//Delete
		DEL_ACTOR_ACTIONS: "DEL_ACTOR_ACTIONS",
		DEL_ACTOR_REQUEST: "DEL_ACTOR_REQUEST",
		DEL_ACTOR_SUCCESS: "DEL_ACTOR_SUCCESS",
		DEL_ACTOR_ERROR: "DEL_ACTOR_ERROR",

//Directors
	//Get All
		GET_DIRECTORS_ACTIONS: "GET_DIRECTORS_ACTIONS",
		GET_DIRECTORS_REQUEST: "GET_DIRECTORS_REQUEST",
		GET_DIRECTORS_SUCCESS: "GET_DIRECTORS_SUCCESS",
		GET_DIRECTORS_ERROR: "GET_DIRECTORS_ERROR",
//Create
		POST_DIRECTOR_ACTIONS: "POST_DIRECTOR_ACTIONS",
		POST_DIRECTOR_REQUEST: "POST_DIRECTOR_REQUEST",
		POST_DIRECTOR_SUCCESS: "POST_DIRECTOR_SUCCESS",
		POST_DIRECTOR_ERROR: "POST_DIRECTOR_ERROR",
//Update
		PUT_DIRECTOR_ACTIONS: "PUT_DIRECTOR_ACTIONS",
		PUT_DIRECTOR_REQUEST: "PUT_DIRECTOR_REQUEST",
		PUT_DIRECTOR_SUCCESS: "PUT_DIRECTOR_SUCCESS",
		PUT_DIRECTOR_ERROR: "PUT_DIRECTOR_ERROR",
//Delete
		DEL_DIRECTOR_ACTIONS: "DEL_DIRECTOR_ACTIONS",
		DEL_DIRECTOR_REQUEST: "DEL_DIRECTOR_REQUEST",
		DEL_DIRECTOR_SUCCESS: "DEL_DIRECTOR_SUCCESS",
		DEL_DIRECTOR_ERROR: "DEL_DIRECTOR_ERROR",

	//Studios
	//Get All
		GET_STUDIOS_ACTIONS: "GET_STUDIOS_ACTIONS",
		GET_STUDIOS_REQUEST: "GET_STUDIOS_REQUEST",
		GET_STUDIOS_SUCCESS: "GET_STUDIOS_SUCCESS",
		GET_STUDIOS_ERROR: "GET_STUDIOS_ERROR",
//Get by id
		GET_STUDIO_ACTIONS: "GET_STUDIOE_REQUEST",
		GET_STUDIO_REQUEST: "GET_STUDIO_REQUEST",
		GET_STUDIO_SUCCESS: "GET_STUDIO_SUCCESS",
		GET_STUDIO_ERROR: "GET_STUDIO_ERROR",
//Create
		POST_STUDIO_ACTIONS: "POST_STUDIO_ACTIONS",
		POST_STUDIO_REQUEST: "POST_STUDIO_REQUEST",
		POST_STUDIO_SUCCESS: "POST_STUDIO_SUCCESS",
		POST_STUDIO_ERROR: "POST_STUDIO_ERROR",
//Update
		PUT_STUDIO_ACTIONS: "PUT_STUDIO_ACTIONS",
		PUT_STUDIO_REQUEST: "PUT_STUDIO_REQUEST",
		PUT_STUDIO_SUCCESS: "PUT_STUDIO_SUCCESS",
		PUT_STUDIO_ERROR: "PUT_STUDIO_ERROR",
//Delete
		DEL_STUDIO_ACTIONS: "DEL_STUDIO_ACTIONS",
		DEL_STUDIO_REQUEST: "DEL_STUDIO_REQUEST",
		DEL_STUDIO_SUCCESS: "DEL_STUDIO_SUCCESS",
		DEL_STUDIO_ERROR: "DEL_STUDIO_ERROR",
}

export default ACTIONS_TYPES;